version: '3.7'
services: 
  mysql:   # 서비스이름
    platform: linux/x86_64
    image: mysql:5.7.32  # 이미지
    container_name: mysql   # 컨테이너 이름
    ports:
      - "3306:3306"   # 포트 설정  외부:내부
    environment:
      MYSQL_ROOT_PASSWORD: "1234"   # 패스워드설정
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_DATABASE: "test"
    command:
      - --character-set-server=utf8mb4      # 인코딩
      # - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init:/docker-entrypoint-initdb.d

# volumes:
#   mysql_volume: